### ISSUE TITLE
Problem reading the secrets?

### ISSUE THREAD

**Issue by ColinLeverger** [dlabsai/mlflow-for-gcp#2]
Hello there,
Thanks for the good tutorial. 
I have followed every instruction but I can’t access the service: the user/password that I try to enter to the nginx auth are not valid. I suspect that there are some problems reading secrets, although I created a service account as described. There are no suspicious logs and I am stuck. I’ve tried to recreate the cloud run few times, same result. 
Any clues on how to debug? :)

**Comment by ColinLeverger** [comment]
As seen in https://stackoverflow.com/questions/62444867/secret-manager-access-denied-despite-correct-roles-for-service-account , the role "Secret Manager Secret Accessor" must be explicitly set at creation of the service accounts time. I'd suggest you add it to the section "Creating a Service Account" of your tutorial :)
Thanks again and cheers!
Colin

**Comment by mateuszKacz** [comment]
Hi Colin!

thanks for trying out this tutorial and for reporting this issue. I’ll update it considering your insight! 

Sorry for the inconvenience and I hope you’ll find this useful anyway. :)

Have a great day,
Mateusz Kaczorek.

**Comment by tszumowski** [comment]
I ran into the same issue regarding roles. I didn't notice it mentioned in the README, so I added it in this PR if you're interested @mateuszKacz:
https://github.com/dlabsai/mlflow-for-gcp/pull/3
